
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CREATE_P ON FOR ALL SELECT INSERT UPDATE DELETE TO PUBLIC CURRENT_USER SESSION_USER USING WITH_C NAME EQUAL BRK_OPEN BRK_CLOSE EXP_END COMMAcreate : CREATE_P name ON table_name for to using with_c EXP_ENDname : NAMEtable_name : NAMEfor :\n\t\t\t| FOR a_s_i_u_da_s_i_u_d : ALL\n\t\t\t| SELECT\n\t\t\t| INSERT\n\t\t\t| UPDATE\n\t\t\t| DELETEto :\n\t\t\t| TO param_commaparam_comma : NAME comma\n\t\t\t\t| PUBLIC comma\n\t\t\t\t| CURRENT_USER comma\n\t\t\t\t| SESSION_USER commacomma :\n\t\t\t\t| param_commausing :\n\t\t\t| USING BRK_OPEN NAME BRK_CLOSEwith_c :\n            | WITH_C BRK_OPEN NAME BRK_CLOSE'
    
_lr_action_items = {'WITH_C':([6,7,8,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,36,],[-4,-3,-11,-19,-8,-6,-5,-9,-7,-10,-12,-17,-17,-17,-17,32,-18,-13,-16,-15,-14,-20,]),'ON':([3,4,],[5,-2,]),'ALL':([9,],[13,]),'NAME':([1,5,10,19,20,21,22,30,35,],[4,7,19,19,19,19,19,33,37,]),'FOR':([6,7,],[9,-3,]),'INSERT':([9,],[12,]),'CREATE_P':([0,],[1,]),'BRK_CLOSE':([33,37,],[36,38,]),'UPDATE':([9,],[15,]),'SESSION_USER':([10,19,20,21,22,],[20,20,20,20,20,]),'TO':([6,7,8,12,13,14,15,16,17,],[-4,-3,10,-8,-6,-5,-9,-7,-10,]),'BRK_OPEN':([23,32,],[30,35,]),'CURRENT_USER':([10,19,20,21,22,],[21,21,21,21,21,]),'USING':([6,7,8,11,12,13,14,15,16,17,18,19,20,21,22,25,26,27,28,29,],[-4,-3,-11,23,-8,-6,-5,-9,-7,-10,-12,-17,-17,-17,-17,-18,-13,-16,-15,-14,]),'EXP_END':([6,7,8,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,31,36,38,],[-4,-3,-11,-19,-8,-6,-5,-9,-7,-10,-12,-17,-17,-17,-17,-21,-18,-13,-16,-15,-14,34,-20,-22,]),'DELETE':([9,],[17,]),'PUBLIC':([10,19,20,21,22,],[22,22,22,22,22,]),'SELECT':([9,],[16,]),'$end':([2,34,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'param_comma':([10,19,20,21,22,],[18,25,25,25,25,]),'with_c':([24,],[31,]),'name':([1,],[3,]),'for':([6,],[8,]),'a_s_i_u_d':([9,],[14,]),'create':([0,],[2,]),'comma':([19,20,21,22,],[26,27,28,29,]),'to':([8,],[11,]),'table_name':([5,],[6,]),'using':([11,],[24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> create","S'",1,None,None,None),
  ('create -> CREATE_P name ON table_name for to using with_c EXP_END','create',9,'p_create','module1.py',72),
  ('name -> NAME','name',1,'p_name','module1.py',76),
  ('table_name -> NAME','table_name',1,'p_table_name','module1.py',80),
  ('for -> <empty>','for',0,'p_for','module1.py',84),
  ('for -> FOR a_s_i_u_d','for',2,'p_for','module1.py',85),
  ('a_s_i_u_d -> ALL','a_s_i_u_d',1,'p_a_s_i_u_d','module1.py',92),
  ('a_s_i_u_d -> SELECT','a_s_i_u_d',1,'p_a_s_i_u_d','module1.py',93),
  ('a_s_i_u_d -> INSERT','a_s_i_u_d',1,'p_a_s_i_u_d','module1.py',94),
  ('a_s_i_u_d -> UPDATE','a_s_i_u_d',1,'p_a_s_i_u_d','module1.py',95),
  ('a_s_i_u_d -> DELETE','a_s_i_u_d',1,'p_a_s_i_u_d','module1.py',96),
  ('to -> <empty>','to',0,'p_to','module1.py',100),
  ('to -> TO param_comma','to',2,'p_to','module1.py',101),
  ('param_comma -> NAME comma','param_comma',2,'p_param_comma','module1.py',108),
  ('param_comma -> PUBLIC comma','param_comma',2,'p_param_comma','module1.py',109),
  ('param_comma -> CURRENT_USER comma','param_comma',2,'p_param_comma','module1.py',110),
  ('param_comma -> SESSION_USER comma','param_comma',2,'p_param_comma','module1.py',111),
  ('comma -> <empty>','comma',0,'p_comma','module1.py',115),
  ('comma -> param_comma','comma',1,'p_comma','module1.py',116),
  ('using -> <empty>','using',0,'p_using','module1.py',123),
  ('using -> USING BRK_OPEN NAME BRK_CLOSE','using',4,'p_using','module1.py',124),
  ('with_c -> <empty>','with_c',0,'p_with_c','module1.py',131),
  ('with_c -> WITH_C BRK_OPEN NAME BRK_CLOSE','with_c',4,'p_with_c','module1.py',132),
]
